### PR TITLE
Fix image magick warnings

### LINKED ISSUE #23: [sr_movements] image magick warnings
```
In file included from /usr/include/ImageMagick-6/Magick++/Include.h:14:0,
                 from /usr/include/ImageMagick-6/Magick++.h:10,
                 from /catkin_melodic_robots/src/sr_tools/sr_movements/include/sr_movements/movement_from_image.hpp:32,
                 from /catkin_melodic_robots/src/sr_tools/sr_movements/src/movement_from_image.cpp:30:
/usr/include/ImageMagick-6/magick/magick-config.h:29:3: warning: #warning "you should set MAGICKCORE_QUANTUM_DEPTH to sensible default set it to configure time default" [-Wcpp]
 # warning "you should set MAGICKCORE_QUANTUM_DEPTH to sensible default set it to configure time default"
   ^~~~~~~
/usr/include/ImageMagick-6/magick/magick-config.h:30:3: warning: #warning "this is an obsolete behavior please fix your makefile" [-Wcpp]
 # warning "this is an obsolete behavior please fix your makefile"
   ^~~~~~~
/usr/include/ImageMagick-6/magick/magick-config.h:52:3: warning: #warning "you should set MAGICKCORE_HDRI_ENABLE to sensible default set it to configure time default" [-Wcpp]
 # warning "you should set MAGICKCORE_HDRI_ENABLE to sensible default set it to configure time default"
   ^~~~~~~
/usr/include/ImageMagick-6/magick/magick-config.h:53:3: warning: #warning "this is an obsolete behavior please fix yours makefile" [-Wcpp]
 # warning "this is an obsolete behavior please fix yours makefile"
```

could you please create a melodic branch there too, then I will provide a PR

### PR DESCRIPTION
**Pull request by guihomework**
fixes #23

### CODE REVIEW

**Comment by AndriyPt** [comment]
@guihomework it seems that rosdep doesn't have this dependency for Bionic 
`sr_ur_robot_hw: No definition of [libuv-dev] for OS version [bionic]`

**Comment by guihomework** [comment]
@AndriyPt  how is this problem related to sr_tools ? I don't even find a reference to sr_ur_robot_hw in sr_tools

**Comment by AndriyPt** [comment]
@guihomework it is 2nd level dependency. So sr_tools depends on sr_interface https://github.com/shadow-robot/sr_tools/blob/melodic-devel/repository.rosinstall#L8
And sr_interface depends on sr_ur_arm (do not ask me why :) ) https://github.com/shadow-robot/sr_interface/blob/melodic-devel/repository.rosinstall#L28
Shippable is getting all these dependencies from source code in order to build sr_tools because we do not have released packages for them (partially thanks to forks). So we need this libuv-dev in Ubuntu Bionic rosdep

**Comment by AndriyPt** [comment]
waiting for this PR to be merged https://github.com/ros/rosdistro/pull/20723

**Pull request merged**
